workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
      # 1.  create Payload  2.  zip into IPA
      - |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -R Runner.app Payload/
        zip -r ../../../app-release.ipa Payload

    artifacts:
      - app-release.ipa        # ← this path is what you “put in artefacts”