name: Dentista
description: Dental ClinicApplication
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.17
  cupertino_icons: ^1.0.8
  uuid: ^4.3.1
  image_picker: ^1.0.4
  path: ^1.8.3
  dots_indicator: ^3.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
